GET http://localhost:3000/api/peliculas

###

GET http://localhost:3000/api/peliculas?s=Dun

###

GET http://localhost:3000/api/peliculas/19

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Película de prueba",
    "sinopsis": "Sinopsis de prueba.",
    "anio": 2024
}

###

PUT http://localhost:3000/api/peliculas/19
Content-Type: application/json

{
    "peliculaid": 19,
    "titulo": "Paw Patrol: La Súper Película",
    "sinopsis": "Un meteorito mágico aterriza en Adventure City y otorga superpoderes a los cachorros de PAW Patrol, convirtiéndolos en The Mighty Pups.",
    "anio": 2024,
    "poster": "https://m.media-amazon.com/images/M/MV5BMGI4NTNlODItMGJlZi00OTIwLTlkM2ItMWFkZjJhZDIzMDc3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_SX300.jpg"
}

###

POST http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "2"
}

###

DELETE http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "1"
}

###

DELETE http://localhost:3000/api/peliculas/19

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "The social network",
    "sinopsis": "La película se basa en múltiples fuentes y se traslada desde los pasillos de Harvard a los cubículos de Palo Alto.",
    "anio": 2024,
    "poster": "https://www.themoviedb.org/t/p/original/jXbqfVHmvCikyTw2Lf5OhKyt9Ym.jpg",
    "categorias": [1, 2]
}

###

GET http://localhost:3000/api/peliculas/17

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Inception",
    "sinopsis": "Un ladrón que roba secretos corporativos mediante el uso de la tecnología de compartición de sueños es encargado con la tarea inversa de implantar una idea en la mente de un CEO.",
    "anio": 2010,
    "poster": "https://www.themoviedb.org/t/p/original/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
    "categorias": ["Ciencia ficción", "Acción", "Aventura"]
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "The Godfather",
    "sinopsis": "El patriarca de una dinastía criminal en Nueva York transfiere el control de su imperio clandestino a su reacio hijo menor.",
    "anio": 1972,
    "poster": "https://www.themoviedb.org/t/p/original/jzDnD5pvYgh9uXaI3IAG0HJlVLv.jpg",
    "categorias": ["Drama", "Crimen"]
}

###

PUT http://localhost:3000/api/peliculas/18
Content-Type: application/json

{
    "titulo": "Inception",
    "sinopsis": "Un ladrón que roba secretos corporativos mediante el uso de la tecnología de compartición de sueños es encargado con la tarea inversa de implantar una idea en la mente de un CEO.",
    "anio": 2010,
    "poster": "https://th.bing.com/th/id/OIP.ULu3ytbiO_JdNVHqx4mqiQHaLH?rs=1&pid=ImgDetMain"
}
